# http://localhost:8080/actuator
# http://localhost:8080/actuator/gateway/routes
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
      http:
        server:
          reactive: DEBUG
      web:
        reactive: DEBUG
